Revert "No need for varargs."
This reverts commit bbc4b9de1bee019a3ee3eae4f9d4c6276428ece4.

I was confused, this works fine:

user=> (defn wtf [system consistency repository-name & {:keys [ttl-fn] :as options}] options)
user=> (wtf 1 2 3)
nil

Yet:
Exception while starting module cassandra-file-api : #<ArityException clojure.lang.ArityException: Wrong number of args (3) passed to: cassandra-repository$cassandra-repository>
clojure.lang.ArityException: Wrong number of args (3) passed to: cassandra-repository$cassandra-repository
at clojure.lang.AFn.throwArity(AFn.java:437)
at clojure.lang.AFn.invoke(AFn.java:47)
at cassandra_file_api.core$start.invoke(core.clj:69)
at clojure.lang.AFn.applyToHelper(AFn.java:163)
at clojure.lang.AFn.applyTo(AFn.java:151)
at clojure.core$apply.invoke(core.clj:617)
at boxure.core$call_in_box.doInvoke(core.clj:230)
at clojure.lang.RestFn.invoke(RestFn.java:464)
at containium.systems.modules.boxes$start_box.invoke(boxes.clj:60)
at containium.systems.modules$do_deploy.invoke(modules.clj:120)
at containium.systems.modules$handle_deploy$fn__4793.invoke(modules.clj:154)
at clojure.core$binding_conveyor_fn$fn__2301.invoke(core.clj:1836)
at clojure.lang.AFn.call(AFn.java:18)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)